apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: 678676043165.dkr.ecr.us-east-2.amazonaws.com/kubernetes-example:latest
        ports:
        - containerPort: 8080
        env:
          - name: SECRET_NAME
            valueFrom:
              secretKeyRef:
                name: hello-secret
                key: name-to-greet

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080